pizzeria/pizzas/urls.py
"""Defines patterns for pizzas"""

from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all pizzas.
    path('pizzas/', views.pizzas_list, name='pizzas_list'),
    # Detail page for a single pizza with all followed toppings.
    path('pizzas_list/<int:pizzas_id>/', views.pizza_page, name='pizza_page'),
]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls'))
]

pizzeria/pizzas/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    """A simple attempt to create a pizza"""
    name = models.CharField(max_length=50)

    def __str__(self):
        """returns a string representation of the model"""
        return self.name


class Topping(models.Model):
    """A topping for pizza"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

# # Maybe I can not use it
#     class Meta:
#         verbose_name_plural = 'toppings'

    def __str__(self):
        """returns a string representation of the model"""
        return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza
# Create your views here.


def index(request):
    """Home page for pizzas app"""
    return render(request, 'pizzas/index.html')


def pizzas_list(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by("name")
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas_list.html', context)


def pizza_page(request, pizzas_id):
    """Show a single pizza and all its toppings"""
    pizza = Pizza.objects.get(id=pizzas_id)
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza_page.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
    <a href="{% url 'pizzas:pizzas_list' %}">Our Pizzas</a>

</p>

{% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Our first WEB-APP for ordering pizza</p>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza_page.html
{% extends "pizzas/base.html" %}

{% block content %}

    <p>Pizza: {{ pizza }}</p>

    <p>Toppings:</p>
    <u1>
    {% for topping in toppings %}
        <li>
            <p>{{ topping }}</p>
        </li>
        {% empty %}
            <li>There are no entries for this topic yet.</li>
        {% endfor %}
    </u1>

{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas_list.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Our Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li><a href="{% url 'pizzas:pizza_page' pizza.id %}">{{ pizza }}</a></li>
    {% empty %}
      <li>No pizzas have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}